netSpending: 88
bequest: 500

maxRothConversion: 100
noRothConversions: "none"
startRothConversions: 2025

withMedicare: "loop"

solver: "HiGHS"
spendingSlack: 0
xorConstraints: true
withSCLoop: true
